### ISSUE TITLE
Use standard POST request on API

### ISSUE THREAD

**Issue by uniibu** [BetKingIO/BetKing-issue-tracker#28]
The POST request on the API uses:
POST http://bkp1api.azurewebsites.net/api/dice/bet?appId=1&chance=90&betAmount=0.1&target=0&currency=0

Use standard POST request by putting the extra parameters to the body of the request and not the url.
Example:
https://i.gyazo.com/b4759a23b7d124305d6c5cba0ffdd1b4.png

**Comment by BetKingIO** [comment]
Agreed. Will clean these api calls up.

**Comment by uniibu** [comment]
please close this issue once you have fixed and updated it so i can be notified and change my code. thanks

**Comment by BetKingIO** [comment]
Committed changes to app sample project
