### ISSUE TITLE
Sample app site not updating?

### ISSUE THREAD

**Issue by uniibu** [BetKingIO/BetKing-issue-tracker#29]
Successfully merged pull request on Sample App master branch does not update the sample site itself.
Example:
https://github.com/BetKingIO/SampleApp/pull/25 - this pull was successfully merged but looking at the sample site http://bkp1sa.azurewebsites.net/ it still shows this https://i.gyazo.com/1ca37c45b78e5b8b402e8c2c3a2c5a59.png

**Comment by BetKingIO** [comment]
Correct.
There's no CI/CD system setup for the sample app yet.

**Comment by BetKingIO** [comment]
Pushed now.
